baseURL: 'https://globalguideracing.netlify.app/'
canonifyURLs: yes
pluralizeListTitles: no
summaryLength: 25
theme: BlogRa
languageCode: en-us
title: Global Guide Racing
disqusShortname: ''
params:
  adsense: 
  contactEmail: your-email@domain.com
  description: The Ultimate Tech Blogging Theme
  facebook: 
  footer: ''
  github: 
  googleAnalytics: ''
  googleSearch: 
  instagram: ''
  linkedin: 
  math: no
  mermaid: no
  pinterest: ''
  twitter: ''
  youtube: 
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - identifier: blog
      name: Blog
      weight: 2
    - name: Posts
      parent: blog
      url: /posts/
      weight: 1
    - name: Sections
      parent: blog
      url: /sections/
      weight: 2
    - name: divider
      parent: blog
      weight: 3
    - name: Tags
      parent: blog
      url: /tags/
      weight: 4
    - identifier: racecards
      name: Racecards
      weight: 3
    - name: Todays Racecards
      parent: racecards
      url: /racecards/today/
      weight: 1
    - name: Contact
      url: /contact/
      weight: 4
markup:
  goldmark:
    parser:
      attribute:
        block: yes
    renderer:
      unsafe: yes
module:
  hugoVersion:
    extended: yes
    min: 0.102.3
