baseURL: 'https://dev-globalguideracing.netlify.app/'
canonifyURLs: yes
pluralizeListTitles: no
summaryLength: 25
theme: Racing
languageCode: en-us
title: Global Guide Racing
disqusShortname: ''
params:
  adsense: 
  contactEmail: your-email@domain.com
  description: The Ultimate Tech Blogging Theme
  facebook: 
  footer: ''
  github: 
  googleAnalytics: ''
  googleSearch: 
  instagram: ''
  linkedin: 
  math: no
  mermaid: no
  pinterest: ''
  twitter: ''
  youtube: 
  hidedate: true
menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
    - identifier: racecards
      name: Racecards
      weight: 2
      pageRef: /racecards/
markup:
  goldmark:
    parser:
      attribute:
        block: yes
    renderer:
      unsafe: yes
module:
  hugoVersion:
    extended: yes
    min: 0.116.0