---
title: "Ayr 2023-02-27"
date: 2023-02-27 
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
options(kableExtra_view_html = F)
```


## Ayr 2023-02-27

This is a test output of the project pegasus algorithm

### Racecard 
<div class="card-body">



```{r echo=FALSE, results = "asis", class.output="card-body"}
library(dplyr)
library(knitr)
library(kableExtra)

#Todays.Prediction <- readRDS('./R_Scripts/Todays_Prediction.rds')

i <- 1
Index <- Todays.Prediction %>% filter(Course=="Ayr") %>% select(QueryID) %>% distinct()

for (i in Index$QueryID) {
  tabledata <- Todays.Prediction %>% filter(QueryID == i)
  racenumber <- tabledata$Race.number[1]
  racename <- tabledata$Title[1]
  raceconditions <- tabledata$Conditions[1]
  cat("#### ", Todays.Prediction[Todays.Prediction$QueryID == i,]$Time.Course[1], "\n")
  cat("\n")

  cat(racename, "\n")
  cat("\n")
  cat('####',raceconditions, "\n")
  cat("\n")
  kibble <-
   tabledata %>% ungroup() %>% filter(QueryID == i) %>% mutate(Silk =
                                                                          "",
                                                                        Alt.VDW=round(Alt.VDW*1000,2),
                                                                        prediction.score=round(prediction.score,3)) %>% select(
                                                                            Horse.Number,
                                                                            Form,
                                                                            Silk,
                                                                            Name,
                                                                            Age,
                                                                            Weight,
                                                                            OR,
                                                                            Trainer,
                                                                            Jockey,
                                                                            VDW.Form,
                                                                            Alt.VDW,
                                                                            prediction.score,
                                                                            Rank,
                                                                            win.pct
                                                                          ) %>%  kable(
                                                                            align = 'clclcccllcclcc',
                                                                            table.attr = "class=\'racecard\'",
                                                                            col.names = c(
                                                                              'No.',
                                                                              "Form",
                                                                              "Horse",
                                                                              "",
                                                                              'Age',
                                                                              'Wt',
                                                                              'OR',
                                                                              'Trainer',
                                                                              'Jockey',
                                                                              'VDW',
                                                                              'Alt VDW',
                                                                              'Pred Score',
                                                                              'Predicted Position',
                                                                              'Win %'
                                                                            )
                                                                          ) %>% kable_styling('hover', full_width = F) %>% column_spec(1, width =
                                                                                                                                         "65px")%>% column_spec(3, width =
                                                                                                                                         "40px")  %>%  column_spec(3, image = Todays.Prediction[Todays.Prediction$QueryID ==
                                                                                                                                                                                                  i,]$url.silk[])
  
  print(kibble)
  cat("\n")
}


```


<\div class="card-body">



### 
